trigger:
- master

pool:
  vmImage: ubuntu-22.04

steps:
- checkout: self
  fetchDepth: 0      # 0 = historique complet ; 1 = clone superficiel
  clean: true

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    mavenOptions: '-Xmx3g'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '17'        # au lieu de 1.11
    jdkArchitectureOption: 'x64'
